misspellings = {
    ' cf ':' of ',
    ' jvill ':' will ',
    ' piaced ':' placed ',
    ' therp ':' there ',
    ' inhabitahts ':' inhabitants ',
    ' pusiWawtHnty.':' pusillanimity.',
    ' Mississirn.':' Mississippi.',
    ' aftei- ':' after ',
    ' tlie ':' the ',
    ' Hugiinots,':' Hugunots,',
    ' toget ':' to get ',
    ' ofhis ':' of his ',
    ' subjectsof ':' subjects of ',
    ' conductof ':' conduct of ',
    ' ahle ':' able ',
    ' ChaHesbourg,':' Charlesbourg,',
    ' hundredand ':' hundred and ',
    ' thjt ':' that ',
    ' inarch ':' march ',
    ' longmonths ':' long months ',
    ' theJiunting ':' the hunting ',
    ' couragejand ':' courage, and ',
    ' issae,':' issue,',
    ' cn ':' on ',
    ' tne ':' the ',
    ' tlie ':' the ',
    ' thoir ':' their ',
    'sayage':'savage',
    ' mv ':' my ',
    'Genera!':'General',
    ' ot ':' of ',
    ' Noith ':' North ',
    ' apd ':' and ',
    ' focd ':' food ',
    ' Apalacliians ':' Apalachians ',
    ' updn ':' upon ',
    ' Apalachjan ':' Apalachian ',
    ' Otorni ':' Otomi ',
    'reaeh':'reach',
    'jvhile':'while',
    'Mianii':'Miami',
    ' liis ':' his ',
    ' goto ':' go to ',
    ' bv ':' by ',
    ' io ':' in ',
    'm#st':'most',
    'conutestible':'contestible'
}
