misspellings = {
    ' cf ':' of ',
    ' jvill ':' will ',
    ' piaced ':' placed ',
    ' therp ':' there ',
    ' inhabitahts ':' inhabitants ',
    ' pusiWawtHnty.':' pusillanimity.',
    ' Mississirn.':' Mississippi.',
    ' aftei- ':' after ',
    ' tlie ':' the ',
    ' Hugiinots,':' Hugunots,',
    ' toget ':' to get ',
    ' ofhis ':' of his ',
    ' subjectsof ':' subjects of ',
    ' conductof ':' conduct of ',
    ' ahle ':' able ',
    ' ChaHesbourg,':' Charlesbourg,',
    ' hundredand ':' hundred and ',
    ' thjt ':' that ',
    ' inarch ':' march ',
    ' longmonths ':' long months ',
    ' theJiunting ':' the hunting ',
    ' couragejand ':' courage, and ',
    ' issae,':' issue,',
    ' cn ':' on ',
    ' tne ':' the ',
    ' thoir ':' their ',
    'sayage':'savage',
    ' mv ':' my ',
    'Genera!':'General',
    ' ot ':' of ',
    ' Noith ':' North ',
    ' apd ':' and ',
    ' focd ':' food ',
    ' Apalacliians ':' Apalachians ',
    ' updn ':' upon ',
    ' Apalachjan ':' Apalachian ',
    ' Otorni ':' Otomi ',
    'reaeh':'reach',
    'jvhile':'while',
    'Mianii':'Miami',
    ' liis ':' his ',
    ' goto ':' go to ',
    ' bv ':' by ',
    ' io ':' in ',
    'm#st':'most',
    'conutestible':'contestible',
    'whicii':'which',
    'organi\'ied':'organized',
    'Novemher': 'November',
    'Hariison':'Harrison',
    'favoi\'able':'favorable',
    'altei\'ations':'alterations',
    'goveniment':'government',
    'govement':'government',
    ' fith ':' fifth ',
    'Sym:ies':'Symmes',
    'determiiio':'determination',
    'o\\vner':'owner',
    'eonsress':'congress',
    'Territoiy':'Territory',
    ']\Iilitia':'Militia',
    'Territoiy':'Territory',
    'Januaiy':'January',
    'Ten-itory':'Territory',
    'perfoiTnance':'performance',
    'Jouiiial':'Journal',
    ' stiled ':' styled ',
    'Recoveiy':'Recovery',
    'refeiences':'references',
    'Heniy':'Henry',
    'tei-ritoi-y':'territory',
    'Jom-nal':'Journal',
    'Mississipy':'Mississipi',
    ' Westm ':' West ',
    'dra%%vTi':'drawn',
    'Govemor':'Governor',
    'Joui-nal':'Journal',
    'setleing':'settling',
    'setled':'settled',
    'Judye':'Judge',
    'oi\'yanized':'organized',
    'territoi-y':'territory',
    'Chailestown':'Charlestown',
    'Januai-y':'January',
    'Territoiy':'Territory',
    'bi\'avery':'bravery',
    'tJie':'the',
    'Inded':'Indeed',
    'militaiy':'military',
    'unifonn':'uniform',
    'wai*riors':'warriors',
    'vei-y':'very',
    'prisones':'prisons',
    'Historii':'History',
    'rioutuos':'riotous',
    'liold':'hold',
    ']\Irs.':'Mrs.',
    'jud^^e':'judge',
    'mariicd':'married',
    'regai\'ds':'regards',
    'Honesf':'Honest',
    'I\'ifle':'rifle',
    'coinmodities':'commodities',
    'ofliees':'officials',
    ' irom ':' from ',
    ' bo ':' be ',
    '?haped':'shaped',
    ' npon ': ' upon ',
    'republies':'republics',
    ' ihose ':' whose ',
    'Louisiaiui':'Louisiana',
    'Xorth':'North',
    ' grund ':' grand ',
    'tlvs':'this',
    'miyht':'might',
    ' vf ':' of ',
    'Congrtti':'Congress',
    '13tb':'13th',
    ' Lome ':' Home ',
    'countrj':'country',
    'suspecling':'suspecting',
    'Obio':'Ohio',
    'Jndge':'Judge',
    'futiil':'futile',
    'shiill':'shall',
    'thc':'the',
    ' fivo ':' five ',
    'magnitnde':'magnitude',
    'Mnjor':'Major',
    ' atid ':' and ',
    ' aud ':' and ',
    ' dnv ':' day ',
    ' raily ':' rally ',
    ' ono ':' one ',
    'stndent':'student',
    ' londer ':' longer ',
    ' ot ':' of ',
    'oli\'er':'offer',
    ' thc ':' the ',
    'conld':'could',
    'Jndge':'Judge',
    ' soou ':' soon ',
    ' aud ':' and ',
    'praticularly':'particulary',
    'difficuly':'difficulty',
    'republies':'republics',
    'Novemher':'November',
    'prejndice':'prejudice',
    'prndent':'prudent',
    'Tegular':'Regular',
    'posssession':'possession',
    'prndence':'prudence',
    'mtended':'intended',
    'jndge':'judge',
    ' mado ':' made ',
    'circiftnstance':'circumstance',
    'accountt':'account',
    'Anmnitions':'Ammunitions',
    'Amunition':'Ammunition',
    'jxissible':'possible',
    ' sculps ':' scalps ',
    ' militin ':' militia ',
    'tbis':'this',
    'frequaint':'frequent',
    'establishmg':'establishing',
    'wiih':'with',
    ' und ':' and ',
    'eorpse':'corpse',
    '1Tbe':'The',
    ' tnose ':' those ',
    ' ipon ':' upon ',
    'Ciief':'Chief',
    ' meu ':' men ',
    ' defent ': ' defeat ',
    'opportuity': 'opportunity',
    'intelhgent':'intelligent',
    'peusious':'pensions',
    'prejndices':'prejudices',
    ' caro ':' care ',
    'Judsre':'Judge',
    'becanse':'because',
    ' thit ':' that ',
    ' tho ':' the ',
    ' trwd ':' tried ',
    'survevors':'surveyors',
    'puhlic':'public',
    'minuto':'minute',
    'Dclawares':'Delawares',
    'hnve':'have',
    'Mississfppi':'Mississipi',
    ' snid ':' said ',
    'weleoming':'welcoming',
    'countrv':'country',
    'pi-actice':'practice',
    ' yeai ':' year ',
    'gi\'ant': 'grant',
    ' couil ':' could ',
    'progi-ess':'progress',
    'counti-y':'country',
    'tennper': 'temper',
    'I\'eason':'reason',
    'injui\'e':'injured',
    'LInited':'United',
    'cari-y':'carry',
    ' roamins ':' roaming ',
    'suHeested':'suggested',
    'proceeings':'proceedings',
    'DoHars':'Dollars',
    'difilcult': 'difficult',
    'difiiculty': 'difficulty',
    'advei-se':'adverse',
    'toKether': 'together',
    'coun2':'count',
    'o\\vner':'owner',
    '\Iilitia':'Militia',
    'Mississipy':'Mississippi',
    'Tx\'ibes':'Tribes',
    ' oi ':' of ',
    'resei-vations':'reservations',
    ' leam ':' learn ',
    'lUinois':'Illinois',
    'disi\'cgard':'disregard',
    'youi\'self':'yourself',
    'yelluw':'yellow',
    'Liws':'Laws',
    ' liws ':' laws ',
    ' liw ':' law ',
    'Liw':'Law',
    ' mss ':' miss ',
    'sei\'ved':'served',
    'STSt': 'St',
    ' sa ': ' so '
}
